import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const URL='https://dmmjlsrdohdzwcyfnlgt.supabase.co';
const KEY='sb_publishable_Nb1BJiz1m9W-qLtiOrJpsw_s6PsrBXi';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'itar-lok-admin-auth'}});
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s||'item').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'item';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let selectedCategory=null;

const style=document.createElement('style');
style.textContent=`.media-panel{border:1px solid #fed7aa;background:#fffaf5;border-radius:18px;padding:14px}.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(92px,1fr));gap:9px;margin-top:10px}.media-tile{position:relative;border:1px solid #e4e4e7;border-radius:13px;background:white;overflow:hidden;aspect-ratio:1}.media-tile img{width:100%;height:100%;object-fit:contain}.media-tile button{position:absolute;right:5px;top:5px;border:0;border-radius:999px;background:#fee2e2;color:#991b1b;width:26px;height:26px;font-weight:900}.pdf-pill{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;background:#fff;border:1px solid #e4e4e7;border-radius:13px;margin-top:8px}`;
document.head.appendChild(style);

function categoryById(id){return selectedCategory?.id===id?selectedCategory:null}
async function loadCategory(id){if(!id){selectedCategory=null;return null}const {data}=await sb.from('categories').select('*').eq('id',id).maybeSingle();selectedCategory=data||null;return selectedCategory}
async function categoryIsBooks(){const id=$('pCategory')?.value;if(!id)return false;const c=await loadCategory(id);return c?.slug==='books'||String(c?.name||'').toLowerCase()==='books'||c?.listing_type==='book'}

// Product media: existing multi-file support is kept, made explicit, previewed, and Books gets one protected PDF.
const pImages=$('pImages');
if(pImages){pImages.multiple=true;const label=pImages.closest('.field')?.querySelector('label');if(label)label.textContent='Upload product images (multiple)';pImages.addEventListener('change',()=>previewPicked(pImages,'productPickedPreview'))}
function previewPicked(input,id){document.getElementById(id)?.remove();const files=[...(input.files||[])];if(!files.length)return;const box=document.createElement('div');box.id=id;box.className='media-grid';for(const f of files){const t=document.createElement('div');t.className='media-tile';const im=document.createElement('img');im.src=URL.createObjectURL(f);im.alt=f.name;t.append(im);box.append(t)}input.closest('.field')?.append(box)}

const pdfPanel=document.createElement('div');pdfPanel.id='bookPdfPanel';pdfPanel.className='media-panel hidden';pdfPanel.innerHTML=`<div><b>Protected book PDF</b><div class="muted" style="font-size:11px;margin-top:3px">PDF only. Stored in a private bucket and served to signed-in readers through short-lived authorization.</div></div><div class="field" style="margin-top:10px"><label>Upload / replace PDF</label><input id="bookPdf" type="file" accept="application/pdf,.pdf"></div><div id="bookPdfStatus"></div>`;
pImages?.closest('.field')?.after(pdfPanel);

async function refreshBookPanel(){const show=await categoryIsBooks();pdfPanel.classList.toggle('hidden',!show);if(!show)return;const id=$('productId')?.value;if(!id){$('bookPdfStatus').innerHTML='<div class="muted" style="font-size:11px;margin-top:8px">Choose a PDF now; it will be attached after the new book is saved.</div>';return}const {data}=await sb.from('book_documents').select('file_name,file_size,updated_at').eq('product_id',id).maybeSingle();$('bookPdfStatus').innerHTML=data?`<div class="pdf-pill"><span><b>${esc(data.file_name||'Book PDF')}</b><br><span class="muted" style="font-size:10px">${data.file_size?Math.round(data.file_size/1024)+' KB':''}</span></span><span class="chip live">PROTECTED</span></div>`:'<div class="muted" style="font-size:11px;margin-top:8px">No PDF uploaded yet.</div>'}
$('pCategory')?.addEventListener('change',()=>{setTimeout(async()=>{const books=await categoryIsBooks();if(books){$('pPrice').value='0';$('pStock').value='';$('pTrack').checked=false}refreshBookPanel()},40)});
document.addEventListener('click',e=>{if(e.target.closest('#newProduct,[data-edit]'))setTimeout(refreshBookPanel,120)});

async function findSavedProduct(started,name,categoryId,existing){if(existing)return existing;for(let i=0;i<30;i++){await sleep(350);const {data}=await sb.from('products').select('id,created_at').eq('name',name).eq('category_id',categoryId).order('created_at',{ascending:false}).limit(1);if(data?.[0]&&new Date(data[0].created_at).getTime()>=started-3000)return data[0].id}return null}
async function saveBookPdf(productId,file){if(!productId||!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))throw new Error('Only PDF files are allowed.');if(file.size>50*1024*1024)throw new Error('PDF must be 50 MB or smaller.');const {data:old}=await sb.from('book_documents').select('storage_path').eq('product_id',productId).maybeSingle();const path=`${productId}/${crypto.randomUUID()}.pdf`;const {error:upErr}=await sb.storage.from('book-pdfs').upload(path,file,{contentType:'application/pdf',cacheControl:'0',upsert:false});if(upErr)throw upErr;const {error:dbErr}=await sb.from('book_documents').upsert({product_id:productId,storage_path:path,file_name:file.name,file_size:file.size,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(dbErr){await sb.storage.from('book-pdfs').remove([path]);throw dbErr}if(old?.storage_path&&old.storage_path!==path)await sb.storage.from('book-pdfs').remove([old.storage_path])}
$('productForm')?.addEventListener('submit',async()=>{const file=$('bookPdf')?.files?.[0];if(!file)return;const books=await categoryIsBooks();if(!books)return;const started=Date.now(),name=$('pName').value.trim(),cat=$('pCategory').value,existing=$('productId').value||null;try{const id=await findSavedProduct(started,name,cat,existing);if(!id)throw new Error('Product saved, but the book record could not be located. Reopen it and upload the PDF.');await saveBookPdf(id,file)}catch(err){alert('PDF upload: '+(err?.message||err))}},false);

// Category image input: true multiple upload + stored category_images records, while categories.image_path remains first/hero for backward compatibility.
const cImage=$('cImage');
if(cImage){cImage.multiple=true;const l=cImage.closest('.field')?.querySelector('label');if(l)l.textContent='Upload category images (multiple)';cImage.addEventListener('change',()=>previewPicked(cImage,'categoryPickedPreview'))}

async function uploadCategoryImages(categoryId,name,files,starting=0){const rows=[];for(let i=0;i<files.length;i++){const f=files[i];if(f.size>5*1024*1024)throw new Error(`${f.name} is larger than 5 MB.`);if(!/^image\/(jpeg|png|webp|avif)$/i.test(f.type))throw new Error(`${f.name} is not a supported image.`);const ext=(f.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`categories/${categoryId}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('product-images').upload(path,f,{contentType:f.type,cacheControl:'3600',upsert:false});if(error)throw error;rows.push({category_id:categoryId,storage_path:path,alt_text:name,sort_order:starting+(i*10)})}if(rows.length){const {error}=await sb.from('category_images').insert(rows);if(error)throw error}return rows}

// Override only category save so all selected category images are persisted; all existing template/category behavior stays compatible.
setTimeout(()=>{const form=$('categoryForm');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const id=$('flexCategoryId')?.value||'',editing=!!id,name=$('cName').value.trim(),files=[...(cImage?.files||[])],type=$('cType')?.value||'normal';if(!name)return alert('Category name is required.');if(!editing&&!files.length)return alert('Choose at least one category image.');let listing_type='normal',option_label=null,option_values=[];if(type!=='normal'){listing_type=type==='book'?'book':'custom';option_label=$('flexCatLabel')?.value.trim()||null;option_values=[...new Set(String($('flexCatValues')?.value||'').split(/[\n,]+/).map(x=>x.trim()).filter(Boolean))];if(listing_type==='custom'&&!option_values.length)return alert('Add at least one option.')}const {data:old}=editing?await sb.from('categories').select('*').eq('id',id).single():{data:null};const payload={name,slug:editing?(old?.slug||slug(name)):slug(name),listing_type,option_label:listing_type==='book'?null:option_label,option_values:listing_type==='book'?[]:option_values,is_published:true,sort_order:editing?(old?.sort_order||0):100};let catId=id;if(editing){const {error}=await sb.from('categories').update(payload).eq('id',id);if(error)return alert(error.message)}else{const {data,error}=await sb.from('categories').insert(payload).select('id').single();if(error)return alert(error.message);catId=data.id}if(files.length){const {count}=await sb.from('category_images').select('id',{count:'exact',head:true}).eq('category_id',catId);const rows=await uploadCategoryImages(catId,name,files,(count||0)*10);if(!old?.image_path&&rows[0])await sb.from('categories').update({image_path:rows[0].storage_path}).eq('id',catId)}$('categoryModal').classList.remove('open');location.reload()};},250);

// Add the special Books type to category editor without removing any existing template types.
setTimeout(()=>{const type=$('cType');if(type&&![...type.options].some(o=>o.value==='book')){const o=document.createElement('option');o.value='book';o.textContent='Books — protected in-app PDF reader';type.insertBefore(o,type.lastElementChild||null)}},350);

// Existing category media manager (add more + delete individual pictures).
async function renderCategoryMedia(){const id=$('flexCategoryId')?.value;if(!id)return;let panel=$('categoryMediaPanel');if(!panel){panel=document.createElement('div');panel.id='categoryMediaPanel';panel.className='media-panel';cImage?.closest('.field')?.after(panel)}const {data}=await sb.from('category_images').select('*').eq('category_id',id).order('sort_order');panel.innerHTML='<b>Category gallery</b><div class="muted" style="font-size:11px">Upload more above, or remove individual images here.</div><div class="media-grid">'+(data||[]).map(x=>`<div class="media-tile"><img src="${esc(/^https?:/i.test(x.storage_path)?x.storage_path:sb.storage.from('product-images').getPublicUrl(x.storage_path).data.publicUrl)}"><button type="button" data-cat-image-delete="${x.id}" data-path="${esc(x.storage_path)}">×</button></div>`).join('')+'</div>';panel.querySelectorAll('[data-cat-image-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this category image?'))return;await sb.from('category_images').delete().eq('id',b.dataset.catImageDelete);if(b.dataset.path&&!/^https?:/i.test(b.dataset.path))await sb.storage.from('product-images').remove([b.dataset.path]);renderCategoryMedia()})}
document.addEventListener('click',e=>{if(e.target.closest('#flexEditCategory'))setTimeout(renderCategoryMedia,180)});

// Clean the private PDF object when a product is deleted (DB row itself cascades).
async function cleanupPdf(id){if(!id)return;const {data}=await sb.from('book_documents').select('storage_path').eq('product_id',id).maybeSingle();if(data?.storage_path)await sb.storage.from('book-pdfs').remove([data.storage_path])}
$('deleteProduct')?.addEventListener('click',()=>cleanupPdf($('productId')?.value));
document.addEventListener('click',e=>{const b=e.target.closest('[data-flex-delete],[data-quick-delete]');if(b)cleanupPdf(b.dataset.flexDelete||b.dataset.quickDelete)});
