import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://dmmjlsrdohdzwcyfnlgt.supabase.co';
const KEY='sb_publishable_Nb1BJiz1m9W-qLtiOrJpsw_s6PsrBXi';
const supabase=createClient(SUPABASE_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'itar-lok-admin-auth'}});
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=p=>`₹${((p||0)/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const templates={normal:{label:null,values:[]},tshirt_size:{label:'Size',values:['S','M','L','XL','2XL']},shoe_size:{label:'Size',values:['6','7','8','9','10']},weight:{label:'Weight',values:['100g','200g','500g','1kg','5kg','10kg']}};
let currentUser=null,mfaFactor=null,productCache=[],categoryCache=[];
function msg(el,type,text){el.innerHTML=text?`<div class="notice ${type}">${esc(text)}</div>`:''}
function setBusy(btn,busy,label){btn.disabled=busy;btn.innerHTML=busy?'<span class="spinner"></span> Working…':label}
function slugify(s){return String(s).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||`item-${Date.now()}`}
function assetUrl(path){if(!path)return'';if(/^https?:\/\//i.test(path))return path;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function signOut(){await supabase.auth.signOut();location.reload()}
$('logout').onclick=signOut;$('mfaLogout').onclick=signOut;
$('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('email').value.trim().toLowerCase(),password=$('password').value;setBusy($('loginBtn'),true,'Sign in securely');const {data,error}=await supabase.auth.signInWithPassword({email,password});setBusy($('loginBtn'),false,'Sign in securely');if(error||!data.user){msg($('authMessage'),'error','Email or password is incorrect.');return}await boot(data.user)};
function showRecovery(){$('loginView').classList.add('hidden');$('mfaView').classList.add('hidden');$('recoveryView').classList.remove('hidden');$('workspace').style.display='none'}
$('forgotPassword').onclick=async()=>{const btn=$('forgotPassword'),email=$('email').value.trim().toLowerCase();if(!email){msg($('authMessage'),'error','Enter your admin email first.');$('email').focus();return}setBusy(btn,true,'Forgot password?');msg($('authMessage'),'info','Sending password reset email…');const redirectTo=location.origin+'/itar-lok-admin/v3.html?recovery=1';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(SUPABASE_URL+'/auth/v1/recover?redirect_to='+encodeURIComponent(redirectTo),{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email}),signal:controller.signal});let payload={};try{payload=await response.json()}catch{}if(!response.ok){throw new Error(payload?.msg||payload?.message||payload?.error_description||payload?.error||('Reset request failed ('+response.status+')'))}msg($('authMessage'),'good','Password reset email sent. Check your inbox and spam folder, then open the reset link.')}catch(error){const message=error?.name==='AbortError'?'The reset request timed out. Please try again.':(error?.message||'Unable to send the password reset email.');msg($('authMessage'),'error',message)}finally{clearTimeout(timeout);setBusy(btn,false,'Forgot password?')}};
$('recoveryForm').onsubmit=async e=>{e.preventDefault();const password=$('newPassword').value,confirm=$('confirmPassword').value;if(password!==confirm){msg($('recoveryMessage'),'error','Passwords do not match.');return}if(password.length<8){msg($('recoveryMessage'),'error','Use at least 8 characters.');return}setBusy($('recoveryBtn'),true,'Update password');const {error}=await supabase.auth.updateUser({password});setBusy($('recoveryBtn'),false,'Update password');if(error){msg($('recoveryMessage'),'error',error.message);return}msg($('recoveryMessage'),'good','Password updated. You can sign in with the new password.');await supabase.auth.signOut();history.replaceState({},'',new URL('./v3.html',location.href).pathname);setTimeout(()=>location.reload(),600)};
async function boot(user){currentUser=user;const {data:admin,error}=await supabase.from('admin_users').select('role').eq('user_id',user.id).maybeSingle();if(error||!admin){await supabase.auth.signOut();$('loginView').classList.remove('hidden');msg($('authMessage'),'error','This account is not authorised for the Devintra owner console.');return}const {data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel!=='aal2'){await showMfa();return}openWorkspace(admin.role)}
async function showMfa(){$('loginView').classList.add('hidden');$('mfaView').classList.remove('hidden');const {data,error}=await supabase.auth.mfa.listFactors();if(error){msg($('mfaMessage'),'error','Unable to check two-factor security.');return}const verified=data?.totp?.find(f=>f.status==='verified');if(verified){mfaFactor=verified;$('mfaText').textContent='Enter the current code from your authenticator app.';return}const {data:enrol,error:ee}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Devintra Owner Console'});if(ee){msg($('mfaMessage'),'error',ee.message);return}mfaFactor=enrol;$('mfaSetup').classList.remove('hidden');$('mfaQr').src=enrol.totp.qr_code;$('mfaText').textContent='First-time setup: scan the QR, then enter the 6-digit code.'}
$('mfaBtn').onclick=async()=>{const code=$('mfaCode').value.replace(/\D/g,'');if(code.length!==6){msg($('mfaMessage'),'error','Enter a 6-digit authenticator code.');return}const factorId=mfaFactor?.id;const {data:ch,error:ce}=await supabase.auth.mfa.challenge({factorId});if(ce){msg($('mfaMessage'),'error',ce.message);return}const {error:ve}=await supabase.auth.mfa.verify({factorId,challengeId:ch.id,code});if(ve){msg($('mfaMessage'),'error','That code was not accepted.');return}location.reload()};
function openWorkspace(role){$('loginView').classList.add('hidden');$('mfaView').classList.add('hidden');$('workspace').style.display='block';$('who').textContent=`${currentUser.email} • ${role}`;loadAll();loadOrders()}
async function loadAll(){await Promise.all([loadCategories(),loadProducts()])}
async function loadCategories(){const {data,error}=await supabase.from('categories').select('*').order('sort_order',{ascending:true}).order('name',{ascending:true});if(error){msg($('catalogMessage'),'error',error.message);return}categoryCache=data||[];renderCategorySelect()}
async function loadProducts(){msg($('catalogMessage'),'info','Loading catalog…');const {data,error}=await supabase.from('products').select('*,product_images(*),product_variants(*)').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){msg($('catalogMessage'),'error',error.message);return}productCache=data||[];msg($('catalogMessage'),'','');renderProducts()}
function renderCategorySelect(selected=''){const sel=$('pCategory');sel.innerHTML='<option value="">Choose category…</option>'+categoryCache.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(selected)sel.value=selected;renderSelectedCategory()}
function renderSelectedCategory(){const c=categoryCache.find(x=>x.id===$('pCategory').value);$('selectedCategoryMini').innerHTML=c?`${c.image_path?`<img src="${esc(assetUrl(c.image_path))}" alt="">`:''}<span><b>${esc(c.name)}</b>${c.listing_type!=='normal'?` • ${esc(c.option_label||'Options')}`:''}</span>`:'Select a category. Existing categories remain unchanged.'}
function imageUrl(p){const path=[...(p.product_images||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0]?.storage_path;return assetUrl(path||'')}
function renderProducts(){const root=$('products');root.innerHTML=productCache.length?'':'<div class="card" style="padding:20px">No products yet.</div>';for(const p of productCache){const el=document.createElement('div');el.className='card product';const variants=(p.product_variants||[]).filter(v=>v.is_active!==false);el.innerHTML=`${imageUrl(p)?`<img class="thumb" src="${esc(imageUrl(p))}" alt="">`:'<div class="thumb"></div>'}<div style="min-width:0;flex:1"><div class="chips"><span class="chip ${p.is_published?'live':'draft'}">${p.is_published?'LIVE':'DRAFT'}</span>${p.category?`<span class="chip">${esc(p.category)}</span>`:''}${variants.length?`<span class="chip">${variants.length} options</span>`:''}</div><h3>${esc(p.name)}</h3><div class="row"><span class="price">${money(p.price_paise)}</span>${p.compare_at_price_paise?`<span class="muted" style="text-decoration:line-through;font-size:12px">${money(p.compare_at_price_paise)}</span>`:''}</div><button class="btn secondary" style="margin-top:9px;padding:7px 10px;font-size:11px" data-edit="${p.id}">Edit</button></div>`;root.appendChild(el)}root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit))}
function selectedCategory(){return categoryCache.find(c=>c.id===$('pCategory').value)||null}
function variantValues(){const c=selectedCategory();return Array.isArray(c?.option_values)?c.option_values:[]}
function addVariantRow(v={}){const row=document.createElement('div');row.className='variantRow';row.innerHTML=`<div><label class="muted" style="font-size:10px;font-weight:800">Option</label><input class="vOption" value="${esc(v.option_value||'')}" placeholder="Size / weight"></div><div><label class="muted" style="font-size:10px;font-weight:800">Price ₹</label><input class="vPrice" type="number" min="0" step="0.01" value="${v.price_paise==null?'':Number(v.price_paise)/100}"></div><div><label class="muted" style="font-size:10px;font-weight:800">MRP ₹</label><input class="vMrp" type="number" min="0" step="0.01" value="${v.compare_at_price_paise==null?'':Number(v.compare_at_price_paise)/100}"></div><div><label class="muted" style="font-size:10px;font-weight:800">Stock</label><input class="vStock" type="number" min="0" step="1" value="${v.stock_quantity??''}"></div><div><label class="muted" style="font-size:10px;font-weight:800">SKU</label><input class="vSku" value="${esc(v.sku||'')}"></div><button type="button" class="btn danger kill">×</button>`;row.querySelector('.kill').onclick=()=>row.remove();$('variantRows').appendChild(row)}
function configureVariants(existing=[]){const c=selectedCategory();const isVariant=c&&c.listing_type!=='normal';$('variantSection').classList.toggle('hidden',!isVariant);if(!isVariant){$('variantRows').innerHTML='';return}$('variantTitle').textContent=`${c.option_label||'Options'} for ${c.name}`;$('variantHelp').textContent='Keep only the options you want to sell. Each option can have its own price, MRP, stock and SKU.';$('variantRows').innerHTML='';if(existing.length){existing.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).forEach(addVariantRow)}else{const base=Number($('pPrice').value||0),mrp=Number($('pCompare').value||0);variantValues().forEach((x,i)=>addVariantRow({option_value:x,price_paise:base?Math.round(base*100):0,compare_at_price_paise:mrp?Math.round(mrp*100):null,stock_quantity:10,sku:`${slugify($('pName').value||c.name).toUpperCase().slice(0,14)}-${String(x).toUpperCase()}`,sort_order:(i+1)*10}))}}
$('pCategory').onchange=()=>{renderSelectedCategory();configureVariants([])};$('addVariant').onclick=()=>addVariantRow();
$('newProduct').onclick=()=>openProduct(null);$('closeModal').onclick=()=>$('productModal').classList.remove('open');
function openProduct(id){const p=productCache.find(x=>x.id===id);$('productForm').reset();$('productId').value=p?.id||'';$('modalTitle').textContent=p?'Edit product':'Add product';$('pName').value=p?.name||'';renderCategorySelect(p?.category_id||categoryCache.find(c=>c.name===p?.category)?.id||'');$('pPrice').value=p?Number(p.price_paise)/100:'';$('pCompare').value=p?.compare_at_price_paise?Number(p.compare_at_price_paise)/100:'';$('pStock').value=p?.stock_quantity??'';$('pShort').value=p?.short_description||'';$('pDescription').value=p?.description||'';$('pTrack').checked=!!p?.track_inventory;$('pFeatured').checked=!!p?.is_featured;$('pPublished').checked=!!p?.is_published;$('deleteProduct').classList.toggle('hidden',!p);$('imagePreview').innerHTML=(p?.product_images||[]).map(i=>`<span class="chip">${esc(i.alt_text||'image')}</span>`).join('');msg($('formMessage'),'','');configureVariants(p?.product_variants||[]);$('productModal').classList.add('open')}
function readVariantRows(){return [...document.querySelectorAll('.variantRow')].map((r,i)=>({option_value:r.querySelector('.vOption').value.trim(),price_paise:Math.round(Number(r.querySelector('.vPrice').value)*100),compare_at_price_paise:r.querySelector('.vMrp').value?Math.round(Number(r.querySelector('.vMrp').value)*100):null,stock_quantity:r.querySelector('.vStock').value===''?null:Number(r.querySelector('.vStock').value),sku:r.querySelector('.vSku').value.trim()||null,is_active:true,sort_order:(i+1)*10}))}
$('productForm').onsubmit=async e=>{e.preventDefault();const id=$('productId').value||null,name=$('pName').value.trim(),cat=selectedCategory();if(!name||!cat){msg($('formMessage'),'error','Enter a product name and choose a category.');return}let variants=cat.listing_type==='normal'?[]:readVariantRows();if(cat.listing_type!=='normal'){if(!variants.length||variants.some(v=>!v.option_value||!Number.isInteger(v.price_paise)||v.price_paise<0)){msg($('formMessage'),'error','Every variant needs an option name and valid price.');return}if(new Set(variants.map(v=>v.option_value.toLowerCase())).size!==variants.length){msg($('formMessage'),'error','Variant option names must be unique.');return}if(variants.some(v=>v.compare_at_price_paise!=null&&v.compare_at_price_paise<v.price_paise)){msg($('formMessage'),'error','Variant MRP cannot be below its selling price.');return}}
let price=Math.round(Number($('pPrice').value)*100),compare=$('pCompare').value?Math.round(Number($('pCompare').value)*100):null;if(variants.length){price=Math.min(...variants.map(v=>v.price_paise));const mrps=variants.map(v=>v.compare_at_price_paise).filter(x=>x!=null);compare=mrps.length?Math.min(...mrps):null}$('pPrice').value=price/100;if(!Number.isInteger(price)||price<0){msg($('formMessage'),'error','Enter a valid price.');return}setBusy($('saveProduct'),true,'Save product');const payload={name,slug:id?(productCache.find(x=>x.id===id)?.slug||slugify(name)):slugify(name),category:cat.name,category_id:cat.id,price_paise:price,compare_at_price_paise:compare,stock_quantity:variants.length?null:($('pStock').value===''?null:Number($('pStock').value)),track_inventory:variants.length?true:$('pTrack').checked,is_featured:$('pFeatured').checked,is_published:$('pPublished').checked,short_description:$('pShort').value.trim()||null,description:$('pDescription').value.trim()||null};let productId=id;if(id){const {error}=await supabase.from('products').update(payload).eq('id',id);if(error){setBusy($('saveProduct'),false,'Save product');msg($('formMessage'),'error',error.message);return}}else{const {data,error}=await supabase.from('products').insert(payload).select('id').single();if(error){setBusy($('saveProduct'),false,'Save product');msg($('formMessage'),'error',error.message);return}productId=data.id}
const files=[...$('pImages').files];for(let i=0;i<files.length;i++){const f=files[i];if(f.size>5*1024*1024){msg($('formMessage'),'error',`${f.name} is larger than 5 MB.`);continue}const ext=(f.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${productId}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await supabase.storage.from('product-images').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type});if(ue){msg($('formMessage'),'error',ue.message);continue}await supabase.from('product_images').insert({product_id:productId,storage_path:path,alt_text:name,sort_order:i})}
const {error:delErr}=await supabase.from('product_variants').delete().eq('product_id',productId);if(delErr){setBusy($('saveProduct'),false,'Save product');msg($('formMessage'),'error',delErr.message);return}if(variants.length){const {error:ve}=await supabase.from('product_variants').insert(variants.map(v=>({...v,product_id:productId})));if(ve){setBusy($('saveProduct'),false,'Save product');msg($('formMessage'),'error',ve.message);return}}setBusy($('saveProduct'),false,'Save product');$('productModal').classList.remove('open');await loadAll()};
$('deleteProduct').onclick=async()=>{const id=$('productId').value;if(!id||!confirm('Delete this product permanently?'))return;const p=productCache.find(x=>x.id===id),paths=(p?.product_images||[]).map(i=>i.storage_path).filter(x=>!/^https?:\/\//i.test(x));if(paths.length)await supabase.storage.from('product-images').remove(paths);const {error}=await supabase.from('products').delete().eq('id',id);if(error){msg($('formMessage'),'error',error.message);return}$('productModal').classList.remove('open');await loadProducts()};
$('addCategory').onclick=()=>{$('categoryForm').reset();$('categoryPreviewName').textContent='New category';$('categoryPreview').classList.add('hidden');$('categoryPreviewPlaceholder').classList.remove('hidden');msg($('categoryMessage'),'','');$('categoryModal').classList.add('open')};$('closeCategoryModal').onclick=()=>$('categoryModal').classList.remove('open');$('cName').oninput=()=>{$('categoryPreviewName').textContent=$('cName').value.trim()||'New category'};$('cImage').onchange=()=>{const f=$('cImage').files?.[0];if(!f)return;const u=URL.createObjectURL(f);$('categoryPreview').src=u;$('categoryPreview').classList.remove('hidden');$('categoryPreviewPlaceholder').classList.add('hidden')};
$('categoryForm').onsubmit=async e=>{e.preventDefault();const name=$('cName').value.trim(),file=$('cImage').files?.[0],type=$('cType').value,t=templates[type]||templates.normal;if(!name||!file){msg($('categoryMessage'),'error','Category name and image are required.');return}if(file.size>5*1024*1024){msg($('categoryMessage'),'error','Category image must be 5 MB or smaller.');return}setBusy($('saveCategory'),true,'Create category');const ext=(file.name.split('.').pop()||'png').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`categories/${slugify(name)}-${crypto.randomUUID()}.${ext}`;const {error:ue}=await supabase.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(ue){setBusy($('saveCategory'),false,'Create category');msg($('categoryMessage'),'error',ue.message);return}const nextSort=(Math.max(0,...categoryCache.map(c=>Number(c.sort_order||0)))+10);const {data,error}=await supabase.from('categories').insert({name,slug:slugify(name),image_path:path,listing_type:type,option_label:t.label,option_values:t.values,is_published:true,sort_order:nextSort}).select().single();if(error){await supabase.storage.from('product-images').remove([path]);setBusy($('saveCategory'),false,'Create category');msg($('categoryMessage'),'error',error.message);return}setBusy($('saveCategory'),false,'Create category');await loadCategories();$('pCategory').value=data.id;renderSelectedCategory();configureVariants([]);$('categoryModal').classList.remove('open')};
async function loadOrders(){const {data,error}=await supabase.from('orders').select('id,order_number,customer_name,customer_email,total_paise,payment_status,fulfillment_status,created_at').order('created_at',{ascending:false}).limit(200);const b=$('ordersBody');if(error){b.innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;return}b.innerHTML=(data||[]).map(o=>`<tr><td>#${o.order_number}</td><td>${esc(o.customer_name||o.customer_email||'—')}</td><td>${money(o.total_paise)}</td><td><span class="chip ${o.payment_status==='paid'?'live':'draft'}">${esc(o.payment_status)}</span></td><td>${esc(o.fulfillment_status)}</td><td>${new Date(o.created_at).toLocaleString('en-IN')}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No orders yet.</td></tr>'}
$('refreshOrders').onclick=loadOrders;document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));$('productsTab').classList.toggle('hidden',btn.dataset.tab!=='products');$('ordersTab').classList.toggle('hidden',btn.dataset.tab!=='orders')});
let recoveryMode=new URLSearchParams(location.search).get('recovery')==='1'||/type=recovery/i.test(location.hash);if(recoveryMode)showRecovery();supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;showRecovery()}});const {data:{session}}=await supabase.auth.getSession();if(session?.user&&!recoveryMode)await boot(session.user);
